name: Docker Image CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        docker login -u ${{ secrets.DOCKER_REGISTRY_USERNAME }} -p ${{ secrets.DOCKER_REGISTRY_PASSWORD }} registry.cybwn.online
        docker build . --file Dockerfile --tag registry.cybwn.online/conjugaison-api:latest
        docker push registry.cybwn.online/conjugaison-api:latest
